using System;
using System.Linq;
using StargateGalacticCommand.Core.Models;
namespace StargateGalacticCommand.Core.Services
{
 public class FleetService{ readonly ShipyardService _ships; public FleetService(ShipyardService ships){_ships=ships;} public int CalculateDistance(PlayerBase a,PlayerBase b){ if(a.PlanetSector.PlanetId==b.PlanetSector.PlanetId) return Math.Max(1,Math.Abs(a.PlanetSector.Number-b.PlanetSector.Number)); return 25+Math.Abs(a.PlanetSector.PlanetId-b.PlanetSector.PlanetId)*10;} public int CalculateFlightSeconds(int distance,ShipTypeDefinition d)=>Math.Max(60,(int)Math.Ceiling(distance*3600.0/d.Speed)); public int CalculateFuelCost(int distance,ShipTypeDefinition d,int count)=>Math.Max(1,distance*d.FuelPerDistance*count);
  public FleetMovement Start(PlayerBase origin,PlayerBase target,FleetMissionType mission,ShipType type,int count,ResourceStock cargo,DateTime now){ if(origin==null||target==null)throw new ArgumentNullException(); if(count<1)throw new ArgumentOutOfRangeException("count"); if(mission!=FleetMissionType.Transport&&mission!=FleetMissionType.Station)throw new InvalidOperationException("Keine Kampffunktion in Version 0.0.7."); var d=_ships.Get(type); if(!d.IsActive)throw new InvalidOperationException("Gesperrter Schiffstyp."); int load=(cargo?.Naquadah??0)+(cargo?.Trinium??0)+(cargo?.Supplies??0)+(cargo?.Energy??0)+(cargo?.Personnel??0); if(load<0)throw new ArgumentOutOfRangeException("cargo"); if(load>d.CargoCapacity*count)throw new InvalidOperationException("Ladung überschreitet Kapazität."); origin.Ships.Remove(type,count); SpendCargo(origin.Resources,cargo); int distance=CalculateDistance(origin,target); int fuel=CalculateFuelCost(distance,d,count); if(origin.Resources.Energy<fuel)throw new InvalidOperationException("Nicht genug Energie/Treibstoff."); origin.Resources.Energy-=fuel; return new FleetMovement{UserId=origin.UserId,OriginBaseId=origin.Id,OriginBase=origin,TargetBaseId=target.Id,TargetBase=target,MissionType=mission,Status=FleetMovementStatus.Outbound,ShipType=type,ShipCount=count,Naquadah=cargo?.Naquadah??0,Trinium=cargo?.Trinium??0,Supplies=cargo?.Supplies??0,Energy=cargo?.Energy??0,Personnel=cargo?.Personnel??0,StartedAtUtc=now,ArrivesAtUtc=now.AddSeconds(CalculateFlightSeconds(distance,d)),Distance=distance,FuelCost=fuel};}
  public FleetReport Complete(FleetMovement m,DateTime now){ if(m.Status==FleetMovementStatus.Completed||m.ArrivesAtUtc>now)throw new InvalidOperationException("Flotte ist noch unterwegs."); if(m.Status==FleetMovementStatus.Outbound){AddCargo(m.TargetBase.Resources,m); if(m.MissionType==FleetMissionType.Station){m.TargetBase.Ships.Add(m.ShipType,m.ShipCount); m.Status=FleetMovementStatus.Completed; m.CompletedAtUtc=now; return R(m,"Stationierung abgeschlossen","Flotte wurde stationiert.");} m.Status=FleetMovementStatus.Returning; m.StartedAtUtc=now; m.ArrivesAtUtc=now.AddSeconds(CalculateFlightSeconds(m.Distance,_ships.Get(m.ShipType))); return R(m,"Transport angekommen","Ressourcen wurden geliefert; Flotte kehrt zurück.");} m.OriginBase.Ships.Add(m.ShipType,m.ShipCount); m.Status=FleetMovementStatus.Completed; m.CompletedAtUtc=now; return R(m,"Flotte zurückgekehrt","Transportflotte ist zurück.");}
  void SpendCargo(ResourceStock r,ResourceStock c){ if(c==null)return; if(r.Naquadah<c.Naquadah||r.Trinium<c.Trinium||r.Supplies<c.Supplies||r.Energy<c.Energy||r.Personnel<c.Personnel)throw new InvalidOperationException("Nicht genug Ressourcen für Ladung."); r.Naquadah-=c.Naquadah; r.Trinium-=c.Trinium; r.Supplies-=c.Supplies; r.Energy-=c.Energy; r.Personnel-=c.Personnel;} void AddCargo(ResourceStock r,FleetMovement m){r.Naquadah+=m.Naquadah;r.Trinium+=m.Trinium;r.Supplies+=m.Supplies;r.Energy+=m.Energy;r.Personnel+=m.Personnel;} FleetReport R(FleetMovement m,string t,string b)=>new FleetReport{UserId=m.UserId,FleetMovement=m,CreatedAtUtc=DateTime.UtcNow,Title=t,Body=b}; }
}
