namespace StargateGalacticCommand.Core.Models
{
    public enum ResearchType
    {
        GateAddressing = 1,
        NaquadahEnergyTechnology = 2,
        ShieldTechnology = 3,
        Hyperdrive = 4,
        Sensorics = 5,
        Medicine = 6,
        StealthTechnology = 7,
        Diplomacy = 8,
        Logistics = 9,
        AdvancedNaquadahRefining = 10,
        AutomatedTriniumExtraction = 11,
        StructuralEngineering = 12,
        AdvancedShipEngineering = 13,
        XenoArchaeology = 14,
        AsgardDataAnalysis = 101,
        Bc304Tactics = 102,
        IrisSecurityProtocols = 103,
        NaquadahReactorMiniaturization = 104,
        AncientOutpostTechnology = 105,
        PrometheusEngineering = 106,
        StargateNetworkMapping = 107,
        AsgardBeamingTechnology = 108,
        ZeroPointModuleTheory = 109,
        StaffWeaponDiscipline = 201,
        HatakCommandStructure = 202,
        JaffaWarriorCode = 203,
        SymbioteEfficiency = 204,
        GroundAssaultTactics = 205,
        FortifiedGarrisons = 206,
        KelNoReemTraining = 207,
        HonorGuardProtocols = 208,
        FreeJaffaNationLogistics = 209,
        CovertInfiltration = 301,
        GoauldSabotage = 302,
        CloakFieldCoordination = 303,
        SymbioteHealing = 304,
        DeepCoverNetworks = 305,
        HostBondingTechnology = 306,
        IntelligenceNetworkExpansion = 307,
        SystemLordDossiers = 308,
        ShadowCouncilInfluence = 309,
        SmugglingRoutes = 401,
        BlackMarketLogistics = 402,
        MercenaryContracts = 403,
        PirateNetworkConnections = 404,
        RuthlessNegotiation = 405,
        StolenTechnologyIntegration = 406,
        HiddenCaches = 407,
        ExtortionNetworks = 408,
        WarlordAmbitions = 409
    }
}
